version: "2"
services:
  explorer-mainnet:
    container_name: explorerMainnet
    restart: always
    build: .
    volumes:
      - /data/mincoin-mainnet:/usr/src/MNCexplorer/data/mincoin/
    ports:                                                    
      - "3000:80"
    links:
      - mainnet

  mainnet:
    container_name: mongoMainnet                                        
    image: mongo
    ports:
      - "27117:27017"                                                   
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - /data/mongodb-mainnet:/data/db
    command: mongod --logpath=/dev/null             
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=explorerdb
      - MONGO_LOG_DIR=/dev/null
